name: CL

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Download softgpu ISO
      run: Invoke-WebRequest https://computernewb.com/isos/driver/softgpu-0.5.2024.24.iso -OutFile softgpu.iso
    - name: Check ISO File Exists
      run: if (Test-Path -Path softgpu.iso) { Write-Output "ISO file exists." } else { throw "ISO file not found." }
    - name: List Directory Contents
      run: Get-ChildItem -Path .
    - name: Unmount Previous ISO (if any)
      run: Dismount-DiskImage -ImagePath $PWD\softgpu.iso || Write-Output "No previous ISO mounted."
    - name: Mount softgpu ISO
      run: Mount-DiskImage -ImagePath $PWD\softgpu.iso
    - name: List Mounted Disks
      run: Get-DiskImage -ImagePath | Select-Object -Property DevicePath
    - name: Install softgpu driver
      run: Start-Process "D:\setup.exe" -ArgumentList '/S' -NoNewWindow -Wait
    - name: Verify softgpu Installation
      run: Get-Process | Select-String "softgpu" | Format-Table -AutoSize
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389

    # New steps for downloading and installing the virtual GPU driver
    
